server {
    listen 80;
    server_name doctor-opus.ru www.doctor-opus.ru doctor-opus.online www.doctor-opus.online;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name doctor-opus.ru www.doctor-opus.ru;

    ssl_certificate     /etc/letsencrypt/live/doctor-opus.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/doctor-opus.ru/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    client_max_body_size 50M;

    location / {
        proxy_pass http://doctor-opus-app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name doctor-opus.online www.doctor-opus.online;

    ssl_certificate     /etc/letsencrypt/live/doctor-opus.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/doctor-opus.online/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    client_max_body_size 50M;

    location / {
        proxy_pass http://doctor-opus-app-en:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
